package entity;
// Generated Apr 2, 2017 9:29:14 AM by Hibernate Tools 4.3.1



/**
 * Kot generated by hbm2java
 */
public class Kot  implements java.io.Serializable {


     private int id;
     private Integer a;

    public Kot() {
    }

    public Kot(Integer a) {
       this.a = a;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getA() {
        return this.a;
    }
    
    public void setA(Integer a) {
        this.a = a;
    }




}


