package entity;
// Generated Apr 2, 2017 9:29:14 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;


/**
 * ProjectRelease generated by hbm2java
 */
@Entity
@Table(name = "PROJECT_RELEASE")
public class ProjectRelease implements java.io.Serializable {

    private int id;
    private Project project;
    private Release release;

    public ProjectRelease() {
    }

    public ProjectRelease(int id) {
        this.id = id;
    }

    public ProjectRelease(int id, Project project, Release release) {
        this.id = id;
        this.project = project;
        this.release = release;
    }

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @JoinColumn(name = "PROJECT_ID")
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @JoinColumn(name = "RELEASE_ID")
    public Release getRelease() {
        return this.release;
    }

    public void setRelease(Release release) {
        this.release = release;
    }
}
