package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Release generated by hbm2java
 */
public class Release  implements java.io.Serializable {


     private int id;
     private int code;
     private Date dateAdded;
     private Integer closed;
     private Date dateClosed;
     private Set releaseVersions = new HashSet(0);

    public Release() {
    }

	
    public Release(int id, int code) {
        this.id = id;
        this.code = code;
    }
    public Release(int id, int code, Date dateAdded, Integer closed, Date dateClosed, Set releaseVersions) {
       this.id = id;
       this.code = code;
       this.dateAdded = dateAdded;
       this.closed = closed;
       this.dateClosed = dateClosed;
       this.releaseVersions = releaseVersions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Integer getClosed() {
        return this.closed;
    }
    
    public void setClosed(Integer closed) {
        this.closed = closed;
    }
    public Date getDateClosed() {
        return this.dateClosed;
    }
    
    public void setDateClosed(Date dateClosed) {
        this.dateClosed = dateClosed;
    }
    public Set getReleaseVersions() {
        return this.releaseVersions;
    }
    
    public void setReleaseVersions(Set releaseVersions) {
        this.releaseVersions = releaseVersions;
    }




}


