package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

/**
 * ReleaseVersion generated by hbm2java
 */
@Entity
@Table(name = "RELEASE_VERSION")
public class ReleaseVersion implements java.io.Serializable {

    private int id;
    private Release release;
    private Version version;

    public ReleaseVersion() {
    }

    public ReleaseVersion(int id) {
        this.id = id;
    }

    public ReleaseVersion(int id, Release release, Version version) {
        this.id = id;
        this.release = release;
        this.version = version;
    }

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @JoinColumn(name = "RELEASE_ID")
    public Release getRelease() {
        return this.release;
    }

    public void setRelease(Release release) {
        this.release = release;
    }

    @JoinColumn(name = "VERSION_ID")
    public Version getVersion() {
        return this.version;
    }

    public void setVersion(Version version) {
        this.version = version;
    }

}
