package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Release generated by hbm2java
 */
@Entity
@Table(name = "RELEASE")
public class Release implements java.io.Serializable {

    private int id;
    private int code;
    private Date dateAdded;
    private Integer closed;
    private Date dateClosed;
    private Set releaseVersions = new HashSet(0);

    public Release() {
    }

    public Release(int id, int code) {
        this.id = id;
        this.code = code;
    }

    public Release(int id, int code, Date dateAdded, Integer closed, Date dateClosed, Set releaseVersions) {
        this.id = id;
        this.code = code;
        this.dateAdded = dateAdded;
        this.closed = closed;
        this.dateClosed = dateClosed;
        this.releaseVersions = releaseVersions;
    }

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "CODE")
    public int getCode() {
        return this.code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_ADDED")
    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @Column(name = "CLOSED")
    public Integer getClosed() {
        return this.closed;
    }

    public void setClosed(Integer closed) {
        this.closed = closed;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_CLOSED")
    public Date getDateClosed() {
        return this.dateClosed;
    }

    public void setDateClosed(Date dateClosed) {
        this.dateClosed = dateClosed;
    }

    /*public Set getReleaseVersions() {
        return this.releaseVersions;
    }

    public void setReleaseVersions(Set releaseVersions) {
        this.releaseVersions = releaseVersions;
    }*/
}
