package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1



/**
 * RevisionFile generated by hbm2java
 */
public class RevisionFile  implements java.io.Serializable {


     private int id;
     private Files files;
     private Revision revision;

    public RevisionFile() {
    }

	
    public RevisionFile(int id) {
        this.id = id;
    }
    public RevisionFile(int id, Files files, Revision revision) {
       this.id = id;
       this.files = files;
       this.revision = revision;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Files getFiles() {
        return this.files;
    }
    
    public void setFiles(Files files) {
        this.files = files;
    }
    public Revision getRevision() {
        return this.revision;
    }
    
    public void setRevision(Revision revision) {
        this.revision = revision;
    }




}


