package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Revision generated by hbm2java
 */
@Entity
@Table(name = "REVISION")
public class Revision implements java.io.Serializable {

    private int id;
    private int revisionNumber;
    private Date dateAdded;
    
    private Release release;

    public Revision() {
    }

    public Revision(int id, int revisionNumber) {
        this.id = id;
        this.revisionNumber = revisionNumber;
    }

    public Revision(int id, int revisionNumber, Date dateAdded) {
        this.id = id;
        this.revisionNumber = revisionNumber;
        this.dateAdded = dateAdded;
    }

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name = "REVISION_NUMBER")
    public int getRevisionNumber() {
        return this.revisionNumber;
    }

    public void setRevisionNumber(int revisionNumber) {
        this.revisionNumber = revisionNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_ADDED")
    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinTable(name = "RELEASE_REVISION", joinColumns = {
        @JoinColumn(name = "REVISION_ID", referencedColumnName = "ID")}, inverseJoinColumns = {
        @JoinColumn(name = "RELEASE_ID", referencedColumnName = "ID")})
    public Release getRelease() {
        return release;
    }

    public void setRelease(Release release) {
        this.release = release;
    }
    
}
