package entity;
// Generated Apr 2, 2017 9:11:23 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Version generated by hbm2java
 */
@Entity
@Table(name = "VERSION")
public class Version implements java.io.Serializable {

    private int id;
    private int versionNumber;
    private Date dateAdded;
    
    private Release release;

    public Version() {
    }

    public Version(int id, int versionNumber) {
        this.id = id;
        this.versionNumber = versionNumber;
    }

    public Version(int id, int versionNumber, Date dateAdded, Set releaseVersions, Set versionRevisions) {
        this.id = id;
        this.versionNumber = versionNumber;
        this.dateAdded = dateAdded;
    }

    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "VERSION_NUMBER")
    public int getVersionNumber() {
        return this.versionNumber;
    }

    public void setVersionNumber(int versionNumber) {
        this.versionNumber = versionNumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_ADDED")
    public Date getDateAdded() {
        return this.dateAdded;
    }

    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }

    @OneToOne(cascade = CascadeType.ALL)
    @JoinTable(name = "RELEASE_VERSION", joinColumns = {
        @JoinColumn(name = "VERSION_ID", referencedColumnName = "ID")}, inverseJoinColumns = {
        @JoinColumn(name = "RELEASE_ID", referencedColumnName = "ID")})
    public Release getRelease() {
        return release;
    }

    public void setRelease(Release release) {
        this.release = release;
    }
}
