SELECT *
FROM PROJECT;

DELETE
FROM PROJECT;

ALTER TABLE PROJECT
ADD UNIQUE (PROJECT_NAME); 

CREATE TABLE RELEASE
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CODE INT UNIQUE NOT NULL,
	DATE_ADDED DATE,
	CLOSED INT,
	DATE_CLOSED DATE
);

CREATE TABLE VERSION
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VERSION_NUMBER INT UNIQUE NOT NULL,
	DATE_ADDED DATE
);

CREATE TABLE RELEASE_VERSION
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RELEASE_ID INT,
	VERSION_ID INT,
	FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID) ON DELETE CASCADE,
	FOREIGN KEY (VERSION_ID) REFERENCES VERSION(ID) ON DELETE CASCADE
);

CREATE TABLE REVISION
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	REVISION_NUMBER INT UNIQUE NOT NULL,
	DATE_ADDED DATE
);

CREATE TABLE VERSION_REVISION
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	VERSION_ID INT,
	REVISION_ID INT,
	FOREIGN KEY (VERSION_ID) REFERENCES VERSION(ID) ON DELETE CASCADE,
	FOREIGN KEY (REVISION_ID) REFERENCES REVISION(ID) ON DELETE CASCADE
);

CREATE TABLE FILES 
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) UNIQUE NOT NULL,
	FILE_PATH VARCHAR(250) NOT NULL,
	DATE_ADDED DATETIME
);

CREATE TABLE REVISION_FILE
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	REVISION_ID INT,
	FILES_ID INT
	FOREIGN KEY (REVISION_ID) REFERENCES REVISION(ID) ON DELETE CASCADE,
	FOREIGN KEY (FILES_ID) REFERENCES FILES(ID) ON DELETE CASCADE
);

CREATE TABLE PROJECT_RELEASE
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	PROJECT_ID INT,
	RELEASE_ID INT,
	FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID) ON DELETE CASCADE,
	FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID) ON DELETE CASCADE,
);

CREATE TABLE RELEASE_REVISION
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RELEASE_ID INT,
	REVISION_ID INT,
	FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID) ON DELETE CASCADE,
	FOREIGN KEY (REVISION_ID) REFERENCES REVISION(ID) ON DELETE CASCADE
);

DROP TABLE RELEASE_VERSION;