package temp;
// Generated Apr 2, 2017 9:29:14 AM by Hibernate Tools 4.3.1



/**
 * ProjectRelease generated by hbm2java
 */
public class ProjectRelease  implements java.io.Serializable {


     private int id;
     private Project project;
     private Release release;

    public ProjectRelease() {
    }

	
    public ProjectRelease(int id) {
        this.id = id;
    }
    public ProjectRelease(int id, Project project, Release release) {
       this.id = id;
       this.project = project;
       this.release = release;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Release getRelease() {
        return this.release;
    }
    
    public void setRelease(Release release) {
        this.release = release;
    }




}


