package temp;
// Generated Apr 2, 2017 9:29:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int id;
     private String projectName;
     private String path;
     private Date dateAdded;
     private Set projectReleases = new HashSet(0);

    public Project() {
    }

	
    public Project(int id, String projectName, String path) {
        this.id = id;
        this.projectName = projectName;
        this.path = path;
    }
    public Project(int id, String projectName, String path, Date dateAdded, Set projectReleases) {
       this.id = id;
       this.projectName = projectName;
       this.path = path;
       this.dateAdded = dateAdded;
       this.projectReleases = projectReleases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Date getDateAdded() {
        return this.dateAdded;
    }
    
    public void setDateAdded(Date dateAdded) {
        this.dateAdded = dateAdded;
    }
    public Set getProjectReleases() {
        return this.projectReleases;
    }
    
    public void setProjectReleases(Set projectReleases) {
        this.projectReleases = projectReleases;
    }




}


