package temp;
// Generated Apr 2, 2017 9:29:14 AM by Hibernate Tools 4.3.1



/**
 * ReleaseVersion generated by hbm2java
 */
public class ReleaseVersion  implements java.io.Serializable {


     private int id;
     private Release release;
     private Version version;

    public ReleaseVersion() {
    }

	
    public ReleaseVersion(int id) {
        this.id = id;
    }
    public ReleaseVersion(int id, Release release, Version version) {
       this.id = id;
       this.release = release;
       this.version = version;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Release getRelease() {
        return this.release;
    }
    
    public void setRelease(Release release) {
        this.release = release;
    }
    public Version getVersion() {
        return this.version;
    }
    
    public void setVersion(Version version) {
        this.version = version;
    }




}


